### PR TITLE
Pr gint test

### PR DESCRIPTION
**Pull request by aliabdolali**
As we discussed, I added ww3_multi option to the global unstructured test in this PR. Please merge it and do your test for ww3_tp2.21 cases (both ww3_shel and ww3_multi cases).
For example, you can use the following to do the test. 
please do not forget to get the tar file from our ftp at the top directory by executing:
`./model/bin/ww3_from_ftp.sh`
for intel compiler:
```
 ./bin/run_test -c intel -S -T -s MPI -s NO_PDLIB -w work_a  -o both -f -p mpirun -n 24 ../model ww3_tp2.21
 ./bin/run_test -c intel -S -T -s MPI -s PDLIB -w work_b -m  -o both -f -p mpirun -n 24 ../model ww3_tp2.21
 ./bin/run_test -c intel -S -T -s MPI -s NO_PDLIB -w work_ma -m grdset_a -o both -f -p mpirun -n 24 ../model ww3_tp2.21
 ./bin/run_test -c intel -S -T -s MPI -s PDLIB -w work_mb -m grdset_b -o both -f -p mpirun -n 24 ../model ww3_tp2.21
```

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali looking at the PR here, this doesn't make sense to add this to @sbrus89 PR on making ww3_grid into separate a callable subroutine: https://github.com/NOAA-EMC/WW3/pull/362 

Furthermore, as @sbrus89 use-case for this development is outside the scope of what is tested with ww3 regression tests, and as I don't think we're going to be adding the coupled model tests that @sbrus89 is using, perhaps as long as the current regression tests all pass, this PR: https://github.com/NOAA-EMC/WW3/pull/362  can go in as is without additional work.

**Comment by sbrus89** [comment]
@aliabdolali and @JessicaMeixner-NOAA , sorry I missed this amongst all my github emails. I'm happy to test this if necessary.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali can you please confirm (perhaps by closing this PR) that this PR is not needed and the next step is to just run the regression tests on the original PR to noaa-emc?

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA sure, I agree with your point.

**Pull request closed without merging**
